### ISSUE TITLE
Bug removing spells from arcade mod

### ISSUE THREAD

**Issue by FoxPace90** [Korzer420/ArcadeKnight#1]
Hey! I'm pretty new to modding so I don't know if anything else had to do with this but I noticed when I exit the mini games you placed throughout the map (this time it was the Gorb one) instead of giving me back my level 2 spells it took them completely away! X( I tried everything I could think of to make it revert but it seems to be permanent, since even the percentage went back (106%->100%). Do you happen to know a solution? Maybe how I can tweak the percentage and give myself the spells? I tried to go back and reclaim them but the game thinks I got them already, so as of now I can't cast anything :')

**Comment by Korzer420** [comment]
Hey, sorry to hear that :/ I'll investigate this. For the mean time, you can use Debug Mod to grant you the spells. Idk though if this restores the percentage. Otherwise you may modify the save data for that save file. If you need help understanding one of these methods, the people in the normal hk discord modding section or the hk modding discord may help you further.

**Comment by Korzer420** [comment]
Fixed it now with 0.3.1. Thanks for the report :) Although this does not restore the abilities that were wrongfully taken from you. You'll need to use debug/save data editor anyway. It might take a bit before this version is available on lumafly/scarab.
